### ISSUE TITLE
Cannot submit jobs from from azure-quantum version 0.15.2101.126940

### ISSUE THREAD

**Issue by viktorveis** [microsoft/qdk-python#19]
```
pip install azure-quantum==0.15.2101.126940
```
0.15.2101.126940 is currently the latest version.

Run any optimization job, for example:

```
from azure.quantum import Workspace
# Provide subscription_id, resource_group, and workspace_name below
workspace = Workspace(subscription_id=subscription_id, resource_group=resource_group, name=workspace_name)
workspace.login()

from azure.quantum.optimization import Problem, ProblemType, Term,  SimulatedAnnealing

problem = Problem(name="Test Problem", problem_type=ProblemType.ising)
terms = [
    Term(w=-9, indices=[0]),
    Term(w=-3, indices=[1,0]),
]
problem.add_terms(terms=terms)
solver = SimulatedAnnealing(workspace, timeout=100)
result = solver.optimize(problem)
print(result)
```

It fails with the following error:
```
Traceback (most recent call last):
  File "c:/src/qio/qio-simple.py", line 14, in <module>
    result = solver.optimize(problem)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\azure\quantum\optimization\solvers.py", line 107, in optimize
    job = self.submit(problem)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\azure\quantum\optimization\solvers.py", line 64, in submit
    container_uri = self.workspace._get_linked_storage_sas_uri(container_name)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\azure\quantum\workspace.py", line 323, in _get_linked_storage_sas_uri
    client = self._create_workspace_storage_client()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\azure\quantum\workspace.py", line 311, in _create_workspace_storage_client
    client = self._create_client().storage
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\azure\quantum\workspace.py", line 303, in _create_client
    client = QuantumClient(auth, self.subscription_id, self.resource_group, self.name, base_url)
TypeError: __init__() takes from 4 to 5 positional arguments but 6 were given
```

A workaround is to install the previous version: `pip install azure-quantum==0.15.2101.125897`

**Comment by guenp** [comment]
Thank you @viktorveis  for filing this bug. The issue was that the wrong commit ID for this repo was pushed to PyPI because of a build pipeline issue.

We have pushed a new release to PyPI with the microversion incremented that contains the correct commit ID.

To get the latest version, run:
```
pip install azure-quantum==0.15.2101.126941
```
or
```
pip install --upgrade azure-quantum
```
