### ISSUE TITLE
[feature/qir-submission] Qiskit QIR - Cirq dependency

### ISSUE THREAD

**Issue by troelsfr** [microsoft/qdk-python#266]
Currently, `cirq` is missing in the install requirements and hence not installed when installing `qiskit-qir`. However, the code depends on cirq:
```
Python 3.9.9 (main, Nov 21 2021, 03:23:44)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import qiskit_qir
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/tfr/Documents/Projects/qdk-python/qiskit-qir/src/qiskit_qir/__init__.py", line 5, in <module>
from qiskit_qir.translate import to_qir, to_qir_bitcode
File "/Users/tfr/Documents/Projects/qdk-python/qiskit-qir/src/qiskit_qir/translate.py", line 5, in <module>
from qiskit_qir.elements import QiskitModule
File "/Users/tfr/Documents/Projects/qdk-python/qiskit-qir/src/qiskit_qir/elements.py", line 7, in <module>
from cirq import num_qubits
ModuleNotFoundError: No module named 'cirq'
>>>
```

**Comment by guenp** [comment]
Thanks @troelsfr! This import should indeed not be there.
