### ISSUE TITLE
[feature/qir-submission] Qiskit QIR - Frontpage example not working

### ISSUE THREAD

**Issue by troelsfr** [microsoft/qdk-python#267]
When running the [frontpage example](https://github.com/microsoft/qdk-python/tree/feature/qir-submission/qiskit-qir):

```
from qiskit import QuantumCircuit
from qiskit_qir import to_qir

circuit = QuantumCircuit(name="my-circuit")
circuit.h(0)
circuit.cx(0, 1)
circuit.cx(1, 2)
circuit.measure([0,1,2], [0, 1, 2])

qir = to_qir(circuit)
```
following output occurs:
```
% python generate_circuit.py
Traceback (most recent call last):
  File "/Users/tfr/Documents/Projects/qat/develop_env/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 1084, in _bit_argument_conversion
    ret = [in_array[bit_representation]]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tfr/Documents/Projects/qat/qir/qir-validation-tests/qiskit/generate_circuit.py", line 5, in <module>
    circuit.h(0)
  File "/Users/tfr/Documents/Projects/qat/develop_env/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 2760, in h
    return self.append(HGate(), [qubit], [])
  File "/Users/tfr/Documents/Projects/qat/develop_env/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 1220, in append
    expanded_qargs = [self.qbit_argument_conversion(qarg) for qarg in qargs or []]
  File "/Users/tfr/Documents/Projects/qat/develop_env/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 1220, in <listcomp>
    expanded_qargs = [self.qbit_argument_conversion(qarg) for qarg in qargs or []]
  File "/Users/tfr/Documents/Projects/qat/develop_env/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 1124, in qbit_argument_conversion
    return QuantumCircuit._bit_argument_conversion(qubit_representation, self.qubits)
  File "/Users/tfr/Documents/Projects/qat/develop_env/lib/python3.9/site-packages/qiskit/circuit/quantumcircuit.py", line 1106, in _bit_argument_conversion
    raise CircuitError("Index out of range.") from ex
qiskit.circuit.exceptions.CircuitError: 'Index out of range.'
```

**Comment by guenp** [comment]
It looks like the sample is missing the classical and quantum register definitions. Thanks for catching this!
